runtime: custom
env: flex
service: drupa_gae
runtime_config:
  document_root : web
  front_controller_file: index.php

network:
  name: VPC_name
  subnetwork_name: Subnet_name

resources:
  cpu: 2
  memory_gb: 4
  disk_size_gb: 20

automatic_scaling:
  min_num_instances: 2
  max_num_instances: 15
  cool_down_period_sec: 180
  target_concurrent_requests: 100
